name: Backend CICD

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker Image
        run: docker build -t christopherpallo2000/cp-update-client-service .
      - name: Publish image to docker hub
        run: docker push christopherpallo2000/cp-update-client-service:latest   

  deploy: 
    needs: build
    runs-on: client-update    
    steps:
      - name: Pull image from docker hub
        run: docker pull christopherpallo2000/cp-update-client-service:latest
      - name: update Old Container
        run: docker rm -f updateclientService || true
      - name: Run docker container
        run: docker run -d --name updateclientService -p 8096:8096 christopherpallo2000/cp-update-client-service